version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: pip
    directory: /requirements/
    schedule:
      interval: weekly
    groups:
      python-requirements:
        patterns:
          - '*'
