# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.12
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: fix-byte-order-marker
-   repo: https://github.com/asottile/pyupgrade
    rev: 75992aaa40730136014f34227e0135f63fc951b4  # frozen: v3.21.2
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
-   repo: https://github.com/psf/black
    rev: 87928e6d6761a4a6d22250e1fee5601b3998086e  # frozen: 26.5.1
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: cfbbfdeb2391c14a37e101e92a77f54f329e1726  # frozen: 7.4.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-implicit-str-concat
-   repo: https://github.com/Riverside-Healthcare/djLint
    rev: b8b8c45322b3f38e5933a8088991b0f0d8cd45c2  # frozen: v1.46.2
    hooks:
      - id: djlint-jinja
        files: "\\.html"
        types_or: ['html']
