coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        # advanced settings
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
        ignore:
          - "flask_security/flask_security/templates"
