[testenv:realpostgres]
dependency_groups = tests
deps =
    psycopg2-binary
commands =
    # Requires that --realdburl be set otherwise doesn't actually use DB
    tox -e compile_catalog
    pytest --basetemp={envtmpdir} {posargs}

[testenv:makedist]
dependency_groups = tests
deps =
    flit
    twine
    check-wheel-contents
commands =
    tox -e compile_catalog
    flit build --no-use-vcs
    check-wheel-contents dist

[testenv:makedist-too]
dependency_groups = tests
deps =
    flit
    twine
    check-wheel-contents
commands =
    tox -e compile_catalog
    flit -f pyproject-too.toml build --no-use-vcs
    check-wheel-contents dist

[testenv:mypy]
dependency_groups = tests
deps =
    mypy
commands =
    mypy --install-types --non-interactive flask_security tests

[testenv:extract_messages]
dependency_groups = babel
skip_install = true
commands =
    pybabel extract --version 5.8.0 --keyword=_fsdomain --project=Flask-Security \
        -o flask_security/translations/flask_security.pot \
        --msgid-bugs-address=jwag956@github.com --mapping-file=babel.ini \
        --add-comments=NOTE flask_security

[testenv:update_catalog]
dependency_groups = babel
skip_install = true
commands =
    pybabel update --domain flask_security -i flask_security/translations/flask_security.pot \
        -d flask_security/translations --no-fuzzy-matching
[flake8]
max-line-length = 88
per-file-ignores =
    tests/view_scaffold.py: E402
