on:
  push:
    tags:
      - "[0-9]+.[0-9]+*"

name: Release

jobs:
  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: update pip
        run: |
          pip install -U wheel setuptools twine
          python -m pip install -U pip
      - name: Create dist
        run: |
          pip install tox
          tox -e makedist
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{secrets.PYPI_API_TOKEN}}
